### ISSUE TITLE
Giscus does not appear when switching blogs via the post navigation.

### ISSUE THREAD

**Issue by Dimasware** [trevortylerlee/astro-micro#32]
The Giscus appears when accessed through the blog page, but if you switch blogs using the previous or next post navigation, the Giscus disappears.

Before moving on to the next blog:
![msedge_Q1XIE8hOHy](https://github.com/trevortylerlee/astro-micro/assets/171955958/ecac846b-897e-4495-9ad4-92feb3a52925)

After moving on to the next (or previous) blog:
![msedge_fKEIVbZNSn](https://github.com/trevortylerlee/astro-micro/assets/171955958/26ef62d4-8049-44c2-98d3-f9d3e0f07db5)

**Comment by trevortylerlee** [comment]
Thank you!
