### ISSUE TITLE
Pagefind should have a better search scope

### ISSUE THREAD

**Issue by luciancah** [trevortylerlee/astro-micro#40]
### Issue

- The Pagefind integrated has a scope of every single page currently, even indexing pagefind component ifself.
<img width="778" alt="스크린샷 2024-07-19 오전 12 50 22" src="https://github.com/user-attachments/assets/0e76afc4-b8d5-442f-83fe-5fda2cde3eb9">

### TO-BE

- Considering the _blog_ domain of the project, it should exclude `root` , `/blog`, `/projects`, and the `Pagefind Component`, preventing double-indexing of recent posts and projects showing on the root as well.

**Comment by miguno** [comment]
Is the 404 page excluded via this PR, too?
